heat_template_version: 2014-10-16

parameters:
  name:
    type: string
  syseleven_net:
    type: string
  image: 
    type: string
  flavor: 
    type: string
  ssh_keys:
    type: comma_delimited_list

resources:

  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image } 
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }    
      networks:
        - port: { get_resource: server_port }

  cloud-init-config:
   # cloud init demo resource
   type: OS::Heat::CloudConfig
   properties:
     cloud_config:
       runcmd:
         - /root/install_generic.sh
         - /root/install_appserver.sh
       write_files:
         -  content: { get_file: scripts/install_generic.sh }
            permissions: 0700
            path: /root/install_generic.sh
         -  content: { get_file: scripts/install_appserver.sh }
            permissions: 0700
            path: /root/install_appserver.sh
       users:
         -  name: syseleven
            gecos:  Service user
            lock-passwd: false
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh-authorized-keys: { get_param: ssh_keys }

  server_port:
    type: OS::Neutron::Port
    properties:
      name: server port
      network_id: { get_param: syseleven_net}

